Vagrant.configure(2) do |config|
    config.vm.box = "rogeriopradoj/xp-ie8"

    config.vm.guest = :windows
    config.vm.boot_timeout = 1
    config.vm.communicator = "winrm"
    config.vm.provider "virtualbox" do |vm|
        vm.gui = true
        vm.memory = "2048"
    end
end